/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author irvin
 */

import javax.swing.JOptionPane;
import java.sql.*;
import database.dbkoneksi;
import java.util.logging.Level;
import java.util.logging.Logger;


public class InsertData extends MainMenu {

    /**
     * Creates new form InsertData
     */
    
    
    Connection conn;
    Statement stmt;
    ResultSet rs;
    dbkoneksi koneksi;
    
    String nama, nim, alamat, fakultas, prodi, idFakultas, idProdi;
    
    public InsertData() {
        try {
            initComponents();
            
            koneksi = new dbkoneksi();
            conn = dbkoneksi.getConnection();
        } catch (SQLException ex) {
            Logger.getLogger(InsertData.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNama = new javax.swing.JTextField();
        jTextFieldNIM = new javax.swing.JTextField();
        jTextFieldAlamat = new javax.swing.JTextField();
        jComboBoxFakultas = new javax.swing.JComboBox<>();
        jComboBoxProdi = new javax.swing.JComboBox<>();
        jButtonSaveDataMahasiswa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Insert Data Mahasiswa"));

        jLabel1.setText("Nama");

        jLabel2.setText("NIM");

        jLabel3.setText("Alamat");

        jLabel4.setText("Fakultas");

        jLabel5.setText("Prodi");

        jTextFieldNama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNamaFocusLost(evt);
            }
        });

        jTextFieldNIM.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNIMFocusLost(evt);
            }
        });

        jComboBoxFakultas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Fakultas", "Teknologi Informasi", "Teknik" }));
        jComboBoxFakultas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxFakultasItemStateChanged(evt);
            }
        });
        jComboBoxFakultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFakultasActionPerformed(evt);
            }
        });

        jButtonSaveDataMahasiswa.setText("Simpan");
        jButtonSaveDataMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveDataMahasiswaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(48, 48, 48)
                        .addComponent(jComboBoxProdi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                            .addComponent(jTextFieldNIM, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                            .addComponent(jTextFieldNama)
                            .addComponent(jComboBoxFakultas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(336, Short.MAX_VALUE)
                .addComponent(jButtonSaveDataMahasiswa)
                .addGap(229, 229, 229))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxFakultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSaveDataMahasiswa)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveDataMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveDataMahasiswaActionPerformed
        // TODO add your handling code here:
          //validasi Nama
        if(jTextFieldNama.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Text Nama Harus Diisi!", "Alert", JOptionPane.INFORMATION_MESSAGE);
         return;
        }
        //validasi nim
        if(jTextFieldNIM.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Text NIM Harus Diisi!", "Alert", JOptionPane.INFORMATION_MESSAGE);
         return;
        }
        
        nama = jTextFieldNama.getText();
        nim = jTextFieldNIM.getText();
        alamat = jTextFieldAlamat.getText();
        fakultas = jComboBoxFakultas.getSelectedItem().toString();
        prodi = jComboBoxProdi.getSelectedItem().toString();
        
        setIDFakultasProdi();
        SimpanData();
        clearForm();
        
    }//GEN-LAST:event_jButtonSaveDataMahasiswaActionPerformed

     private void checkNama() {
        boolean checkNama;
        nama = jTextFieldNama.getText().toString();
        String ErrorNama = "Nama Hanya Terdiri dari Karakter huruf a - Z";

        checkNama = nama.matches("[a-zA-Z\s]+");

        if (checkNama == false) {
            JOptionPane.showMessageDialog(null, ErrorNama, "Alert", JOptionPane.INFORMATION_MESSAGE);
            jTextFieldNama.setText("");
        }

    }
    
    private void jTextFieldNamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNamaFocusLost
        // TODO add your handling code here:
        checkNama();
    }//GEN-LAST:event_jTextFieldNamaFocusLost
 //validasi Nim
    private void checkNim() {
        boolean checkNim;
        nim = jTextFieldNIM.getText().toString();
        String ErrorNama = "Nim Hanya Terdiri dari Angka sebanyak 10 Digit";

        checkNim = nim.matches("[0-9]{10}$");

        if (checkNim == false) {
            JOptionPane.showMessageDialog(null, ErrorNama, "Alert", JOptionPane.INFORMATION_MESSAGE);
            jTextFieldNIM.setText("");
        }

    }
    private void jTextFieldNIMFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNIMFocusLost
        // TODO add your handling code here:
        checkNim();
    }//GEN-LAST:event_jTextFieldNIMFocusLost

    private void jComboBoxFakultasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxFakultasItemStateChanged
        // TODO add your handling code here:
        setProdi();
    }//GEN-LAST:event_jComboBoxFakultasItemStateChanged

    private void jComboBoxFakultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFakultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFakultasActionPerformed

    private void setProdi(){
        fakultas = jComboBoxFakultas.getSelectedItem().toString();
        
        if(fakultas.equalsIgnoreCase("Teknologi Informasi")){
            jComboBoxProdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Teknik Informatika", "Sistem Informasi"}));
        }else if(fakultas.equalsIgnoreCase("Teknik")){
            jComboBoxProdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Sipil","Arsitektur"}));
        }else{
            jComboBoxProdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{""}));
        }
        
    }
    
    private void setIDFakultasProdi(){
        if(fakultas.equalsIgnoreCase("Teknologi Informasi")){
            idFakultas="KF001";
            if(prodi.equalsIgnoreCase("Teknik Informatika")){
                idProdi="KP001";
            }else if(prodi.equalsIgnoreCase("Sistem Informasi")){
                idProdi="KP002";
            }
        }
        else if(fakultas.equalsIgnoreCase("Teknik")){
            idFakultas="KF002";
            if(prodi.equalsIgnoreCase("Sipil")){
                idProdi="KP003";
            }else if(prodi.equalsIgnoreCase("Arsitektur")){
                idProdi="KP004";
            }
        }
    }
    
    
    private boolean SimpanData(){
        try {
            stmt = conn.createStatement();
            int simpan = stmt.executeUpdate("INSERT INTO mahasiswa(nim,nama,alamat,kodeprodi,kodefakultas) VALUES ('"+nim+"','"+nama+"','"+alamat+"','"+idProdi+"','"+idFakultas+"')");
            
            
            if (simpan ==1){
                JOptionPane.showMessageDialog(rootPane,"Data tersimpan");
            }
            return true;
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"error" + ex.getMessage());
        }
        return false;
    }
    
    private void clearForm(){
        jTextFieldNIM.setText("");
        jTextFieldNama.setText("");
        jTextFieldAlamat.setText("");
        jComboBoxFakultas.setSelectedIndex(0);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSaveDataMahasiswa;
    private javax.swing.JComboBox<String> jComboBoxFakultas;
    private javax.swing.JComboBox<String> jComboBoxProdi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldAlamat;
    private javax.swing.JTextField jTextFieldNIM;
    private javax.swing.JTextField jTextFieldNama;
    // End of variables declaration//GEN-END:variables
}
