/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author irvin
 */
import database.dbkoneksi;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

public class UpdateDeleteData extends javax.swing.JFrame {

    /**
     * Creates new form UpdateDeleteData
     */
        Connection conn;
    Statement stmt;
    ResultSet rs;
    dbkoneksi koneksi;
    
    String nama, nim, alamat, fakultas, prodi, idFakultas, idProdi,cariNIM;
    public UpdateDeleteData() {
         try {
            initComponents();
            
            koneksi = new dbkoneksi();
            conn = dbkoneksi.getConnection();
        } catch (SQLException ex) {
            Logger.getLogger(InsertData.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNama = new javax.swing.JTextField();
        jTextFieldNIM = new javax.swing.JTextField();
        jTextFieldAlamat = new javax.swing.JTextField();
        jComboBoxFakultas = new javax.swing.JComboBox<>();
        jComboBoxProdi = new javax.swing.JComboBox<>();
        jButtonSaveDataMahasiswa = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCariNIM = new javax.swing.JTextField();
        jButtonCari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Insert Data Mahasiswa"));

        jLabel1.setText("Nama");

        jLabel2.setText("NIM");

        jLabel3.setText("Alamat");

        jLabel4.setText("Fakultas");

        jLabel5.setText("Prodi");

        jTextFieldNama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNamaFocusLost(evt);
            }
        });

        jTextFieldNIM.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNIMFocusLost(evt);
            }
        });

        jComboBoxFakultas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Fakultas", "Teknologi Informasi", "Teknik" }));
        jComboBoxFakultas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxFakultasItemStateChanged(evt);
            }
        });

        jButtonSaveDataMahasiswa.setText("Simpan");
        jButtonSaveDataMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveDataMahasiswaActionPerformed(evt);
            }
        });

        jButtonHapus.setText("Hapus");
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(48, 48, 48)
                                .addComponent(jComboBoxProdi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldAlamat)
                                    .addComponent(jTextFieldNIM)
                                    .addComponent(jTextFieldNama)
                                    .addComponent(jComboBoxFakultas, 0, 243, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jButtonSaveDataMahasiswa)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonHapus)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxFakultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSaveDataMahasiswa)
                    .addComponent(jButtonHapus))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel6.setText("NIM");

        jTextFieldCariNIM.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCariNIMFocusLost(evt);
            }
        });

        jButtonCari.setText("Cari");
        jButtonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(33, 33, 33)
                .addComponent(jTextFieldCariNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCari)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jTextFieldCariNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonCari))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
  private void checkNama() {
        boolean checkNama;
        nama = jTextFieldNama.getText().toString();
        String ErrorNama = "Nama Hanya Terdiri dari Karakter huruf a - Z";

        checkNama = nama.matches("[a-zA-Z\s]+");

        if (checkNama == false) {
            JOptionPane.showMessageDialog(null, ErrorNama, "Alert", JOptionPane.INFORMATION_MESSAGE);
            jTextFieldNama.setText("");
        }

    }
    private void jTextFieldNamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNamaFocusLost
        // TODO add your handling code here:
        checkNama();
    }//GEN-LAST:event_jTextFieldNamaFocusLost
  private void checkNim() {
        boolean checkNim;
        nim = jTextFieldNIM.getText().toString();
        String ErrorNama = "Nim Hanya Terdiri dari Angka sebanyak 10 Digit";

        checkNim = nim.matches("[0-9]{10}$");

        if (checkNim == false) {
            JOptionPane.showMessageDialog(null, ErrorNama, "Alert", JOptionPane.INFORMATION_MESSAGE);
            jTextFieldNIM.setText("");
        }

    }
    private void jTextFieldNIMFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNIMFocusLost
        // TODO add your handling code here:
        checkNim();
    }//GEN-LAST:event_jTextFieldNIMFocusLost
 private void setProdi(){
        fakultas = jComboBoxFakultas.getSelectedItem().toString();
        
        if(fakultas.equalsIgnoreCase("Teknologi Informasi")){
            jComboBoxProdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Teknik Informatika", "Sistem Informasi"}));
        }else if(fakultas.equalsIgnoreCase("Teknik")){
            jComboBoxProdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Sipil","Arsitektur"}));
        }else{
            jComboBoxProdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{""}));
        }
        
    }
    
    private void setIDFakultasProdi(){
        if(fakultas.equalsIgnoreCase("Teknologi Informasi")){
            idFakultas="KF001";
            if(prodi.equalsIgnoreCase("Teknik Informatika")){
                idProdi="KP001";
            }else if(prodi.equalsIgnoreCase("Sistem Informasi")){
                idProdi="KP002";
            }
        }
        else if(fakultas.equalsIgnoreCase("Teknik")){
            idFakultas="KF002";
            if(prodi.equalsIgnoreCase("Sipil")){
                idProdi="KP003";
            }else if(prodi.equalsIgnoreCase("Arsitektur")){
                idProdi="KP004";
            }
        }
    }
    
    private void jComboBoxFakultasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxFakultasItemStateChanged
        // TODO add your handling code here:
        setProdi();
    }//GEN-LAST:event_jComboBoxFakultasItemStateChanged

    private void jButtonSaveDataMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveDataMahasiswaActionPerformed
        // TODO add your handling code here:
        //validasi Nama
        if(jTextFieldNama.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Text Nama Harus Diisi!", "Alert", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        //validasi nim
        if(jTextFieldNIM.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Text NIM Harus Diisi!", "Alert", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        nama = jTextFieldNama.getText();
        nim = jTextFieldNIM.getText();
        alamat = jTextFieldAlamat.getText();
        fakultas = jComboBoxFakultas.getSelectedItem().toString();
        prodi = jComboBoxProdi.getSelectedItem().toString();

        setIDFakultasProdi();
        EditData();
        clearForm();

    }//GEN-LAST:event_jButtonSaveDataMahasiswaActionPerformed

    private boolean EditData(){
          if(jTextFieldCariNIM.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Text Cari NIM Harus Diisi!", "Alert", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        try {
            stmt = conn.createStatement();
            
            int update = stmt.executeUpdate("UPDATE mahasiswa SET nim ='"+nim+"',nama ='"+nama+"',alamat='"+alamat+"',kodeprodi ='"+idProdi+"',kodefakultas ='"+idFakultas +"' "
                    + " WHERE nim = '"+cariNIM+"'");
            if(update ==1){
                JOptionPane.showMessageDialog(rootPane,"data berhasil Diubah");
            }
            return true;
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null,"error" + ex.getMessage());
        }
        return false;
    }
    
    private void clearForm(){
        jTextFieldNIM.setText("");
        jTextFieldNama.setText("");
        jTextFieldAlamat.setText("");
        jComboBoxFakultas.setSelectedIndex(0);
    }
    private void jTextFieldCariNIMFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCariNIMFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCariNIMFocusLost

    private void jButtonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCariActionPerformed
        // TODO add your handling code here:
        cariNIM = jTextFieldCariNIM.getText();
        
        cariMahasiswa();
        setNamaFakultasProdi();
        tampilData();
        
    }//GEN-LAST:event_jButtonCariActionPerformed

    private void cariMahasiswa(){
        String sql = "SELECT * from mahasiswa WHERE nim ='"+ cariNIM +"'";
        
        
        try{
            stmt = conn.createStatement();
            rs = stmt.executeQuery(sql);
            
            
            while(rs.next()){
                if(rs.getString("nim").isEmpty()){
                    JOptionPane.showMessageDialog(rootPane,"NIM Tidak Terdaftar");
                }else{
                    nama = rs.getString("nama");
                    nim = rs.getString("nim");
                    alamat = rs.getString("alamat");
                    idFakultas=rs.getString("kodefakultas");
                    idProdi=rs.getString("kodeprodi");
                }
            }
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
                
    }
    
    
    private void setNamaFakultasProdi(){
        if(idFakultas.equalsIgnoreCase("KF001")){
            fakultas="Teknologi Informasi";
            if(idProdi.equalsIgnoreCase("KP001")){
                prodi="Teknik Informatika";
            }else if(idProdi.equalsIgnoreCase("KP002")){
                prodi="Sistem Informasi";
            }
        }else if(idFakultas.equalsIgnoreCase("KF002")){
            fakultas="Teknik";
            if(idProdi.equalsIgnoreCase("KP003")){
                prodi ="Sipil";
            }else if(idProdi.equalsIgnoreCase("KP004")){
                prodi ="Arsitektur";
            }
        }
    }
    
    private void tampilData(){
        jTextFieldNIM.setText(nim);
        jTextFieldNama.setText(nama);
        jTextFieldAlamat.setText(alamat);
        jComboBoxFakultas.setSelectedItem(fakultas);
        jComboBoxProdi.setSelectedItem(prodi);
    }
    
    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed

        // TODO add your handling code here:
        hapusMahasiswa();
        clearForm();
    }//GEN-LAST:event_jButtonHapusActionPerformed

    private boolean hapusMahasiswa(){
         if(jTextFieldCariNIM.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Text Cari NIM Harus Diisi!", "Alert", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        try {
              stmt = conn.createStatement();
              int delete = stmt.executeUpdate("DELETE FROM mahasiswa WHERE nim ='"+nim+"'");
              if (delete ==1){
                  JOptionPane.showMessageDialog(rootPane,"data berhasil dihapus");
              }
              return true;
        } catch (SQLException e) {
             JOptionPane.showMessageDialog(rootPane, e);
        }
        return false;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateDeleteData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateDeleteData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateDeleteData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateDeleteData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateDeleteData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCari;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonSaveDataMahasiswa;
    private javax.swing.JComboBox<String> jComboBoxFakultas;
    private javax.swing.JComboBox<String> jComboBoxProdi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldAlamat;
    private javax.swing.JTextField jTextFieldCariNIM;
    private javax.swing.JTextField jTextFieldNIM;
    private javax.swing.JTextField jTextFieldNama;
    // End of variables declaration//GEN-END:variables
}
